# change the version number in case of a release build
package:
  name: pychrono
  version: 7.0.0

source:
  path: ../../..

build:
  rpaths:
    - lib/
  script_env:

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true
  
requirements:
  build:
    - python
    - cmake   # [not win]
    - ninja   # [linux or osx]
    - swig
    - mkl ==2023.0.0 # [not arm64]
    - mkl-devel ==2023.0.0 # [not arm64]
    - irrlicht ==1.8.5
    - occt ==7.4.0
    - numpy >=1.24.0
    - glew
    - glfw
    - eigen ==3.4.0

  run:
    - python
    - pythonocc-core ==7.4.0
    - mkl ==2023.0.0 # [not arm64]
    - numpy >=1.24.0
    - irrlicht ==1.8.5
    - glew
    - glfw

test:
  requires:
    - wxpython          [py27]
    - pyside            [py27]

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  summary: A physics engine for constrained multi-flexible-body dynamics

